/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    staff: Staff;
    customers: Customer;
    countries: Country;
    visas: Visa;
    services: Service;
    'service-requests': ServiceRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    staff: StaffSelect<false> | StaffSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    visas: VisasSelect<false> | VisasSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-requests': ServiceRequestsSelect<false> | ServiceRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'consultation-page': ConsultationPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'consultation-page': ConsultationPageSelect<false> | ConsultationPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  roles: ('admin' | 'consultant' | 'caseOperator' | 'financeOperator' | 'contentEditor')[];
  accountStatus: 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff';
}
/**
 * حساب مشتریان سایت برای رزرو و پیگیری خدمات.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  /**
   * مانند 09121234567 یا +989121234567
   */
  mobile: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  flag: string;
  summary: string;
  introduction: string;
  embassyAppointment?: {
    enabled?: boolean | null;
    /**
     * تا زمان ساخت فرم ثبت درخواست، این گزینه را خاموش نگه دارید.
     */
    acceptingRequests?: boolean | null;
    title?: string | null;
    /**
     * این متن روی کارت کشور در صفحه وقت سفارت نمایش داده می‌شود.
     */
    summary?: string | null;
    introduction?: string | null;
    requiredDocuments?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    importantNotes?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    estimatedTime?: string | null;
    feeNote?: string | null;
    /**
     * لینک رسمی سفارت، کارگزاری یا سامانه رزرو وقت.
     */
    officialSourceUrl?: string | null;
    lastReviewedAt?: string | null;
  };
  /**
   * فقط حروف کوچک انگلیسی، عدد و خط تیره؛ مانند canada
   */
  slug: string;
  /**
   * مانند CA یا DE
   */
  code: string;
  featuredOnHomepage?: boolean | null;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visas".
 */
export interface Visa {
  id: number;
  country: number | Country;
  title: string;
  category: 'visitor' | 'study' | 'work' | 'family' | 'transit' | 'other';
  summary: string;
  suitableFor?: string | null;
  processingTime?: string | null;
  validity?: string | null;
  stayLength?: string | null;
  feeNote?: string | null;
  requirements: {
    kind: 'required' | 'conditional' | 'later';
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  steps: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  officialSourceLabel: string;
  /**
   * لینک باید با https:// شروع شود.
   */
  officialSourceUrl: string;
  lastReviewedAt: string;
  disclaimer?: string | null;
  /**
   * فقط حروف کوچک انگلیسی، عدد و خط تیره؛ مانند visitor
   */
  slug: string;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * خدمات قابل نمایش در سایت، مانند خدمات ویزا، وقت سفارت و مشاوره.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  kind: 'visa' | 'embassyAppointment' | 'consultation' | 'documentReview';
  /**
   * این متن در کارت خدمت در صفحه فهرست نمایش داده می‌شود.
   */
  summary: string;
  /**
   * توضیح کامل و ساده‌ای که مشتری در صفحه اختصاصی خدمت می‌خواند.
   */
  description: string;
  benefits: {
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  steps: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  pricingMode: 'fixed' | 'quotation';
  /**
   * فقط عدد وارد کنید؛ برای مثال 2500000.
   */
  priceAmount?: number | null;
  estimatedDuration?: string | null;
  /**
   * فقط حروف انگلیسی کوچک، عدد و خط تیره؛ مانند visa-services
   */
  slug: string;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * درخواست‌های خدمات و وقت سفارت ثبت‌شده توسط مشتریان.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests".
 */
export interface ServiceRequest {
  id: number;
  reference: string;
  customer: number | Customer;
  requestType: 'service' | 'embassyAppointment';
  service?: (number | null) | Service;
  country?: (number | null) | Country;
  status:
    | 'submitted'
    | 'needsDocuments'
    | 'underReview'
    | 'quoted'
    | 'awaitingPayment'
    | 'paymentReview'
    | 'inProgress'
    | 'completed'
    | 'rejected'
    | 'cancelled';
  submittedAt: string;
  applicant: {
    fullName: string;
    mobile: string;
    email: string;
    nationality: string;
    /**
     * در صورت آماده بودن پاسپورت وارد شود.
     */
    passportNumber?: string | null;
    applicantsCount: number;
  };
  customerMessage?: string | null;
  /**
   * برای خدماتی که قیمت آن‌ها پس از بررسی اعلام می‌شود.
   */
  quotedAmount?: number | null;
  /**
   * این متن فعلاً فقط در پنل مدیریت نمایش داده می‌شود.
   */
  staffNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'visas';
        value: number | Visa;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-requests';
        value: number | ServiceRequest;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'staff';
        value: number | Staff;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'staff';
        value: number | Staff;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  accountStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  mobile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  flag?: T;
  summary?: T;
  introduction?: T;
  embassyAppointment?:
    | T
    | {
        enabled?: T;
        acceptingRequests?: T;
        title?: T;
        summary?: T;
        introduction?: T;
        requiredDocuments?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        importantNotes?:
          | T
          | {
              text?: T;
              id?: T;
            };
        estimatedTime?: T;
        feeNote?: T;
        officialSourceUrl?: T;
        lastReviewedAt?: T;
      };
  slug?: T;
  code?: T;
  featuredOnHomepage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visas_select".
 */
export interface VisasSelect<T extends boolean = true> {
  country?: T;
  title?: T;
  category?: T;
  summary?: T;
  suitableFor?: T;
  processingTime?: T;
  validity?: T;
  stayLength?: T;
  feeNote?: T;
  requirements?:
    | T
    | {
        kind?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  officialSourceLabel?: T;
  officialSourceUrl?: T;
  lastReviewedAt?: T;
  disclaimer?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  summary?: T;
  description?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  pricingMode?: T;
  priceAmount?: T;
  estimatedDuration?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests_select".
 */
export interface ServiceRequestsSelect<T extends boolean = true> {
  reference?: T;
  customer?: T;
  requestType?: T;
  service?: T;
  country?: T;
  status?: T;
  submittedAt?: T;
  applicant?:
    | T
    | {
        fullName?: T;
        mobile?: T;
        email?: T;
        nationality?: T;
        passportNumber?: T;
        applicantsCount?: T;
      };
  customerMessage?: T;
  quotedAmount?: T;
  staffNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    kicker: string;
    title: string;
    accent: string;
    description: string;
    primaryActionLabel: string;
    primaryActionHref: string;
    secondaryActionLabel: string;
    secondaryActionHref: string;
    highlights?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  destinationIntro: {
    kicker: string;
    title: string;
    description: string;
  };
  serviceIntro: {
    kicker: string;
    title: string;
    description: string;
  };
  services?:
    | {
        index: string;
        eyebrow: string;
        title: string;
        description: string;
        actionLabel: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  process: {
    kicker: string;
    title: string;
    description: string;
    steps?:
      | {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  trust: {
    kicker: string;
    title: string;
    description: string;
    actionLabel: string;
    actionHref: string;
  };
  consultation: {
    kicker: string;
    title: string;
    description: string;
    actionLabel: string;
    actionHref: string;
  };
  faqIntro: {
    kicker: string;
    title: string;
    description: string;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        category: 'visa-services' | 'documents' | 'consultation-payment';
        showOnHomepage?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * متن، قیمت، مدت و اطلاعات صفحه مشاوره را از این قسمت مدیریت کنید.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-page".
 */
export interface ConsultationPage {
  id: number;
  hero: {
    kicker: string;
    title: string;
    description: string;
  };
  durationMinutes: number;
  /**
   * اگر هنوز قیمت مشخص نیست، عدد صفر وارد کنید.
   */
  priceAmount: number;
  deliveryMethod: 'video' | 'phone' | 'inPerson';
  documentsNote: string;
  paymentNote: string;
  cancellationPolicy: string;
  benefits: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  steps: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        accent?: T;
        description?: T;
        primaryActionLabel?: T;
        primaryActionHref?: T;
        secondaryActionLabel?: T;
        secondaryActionHref?: T;
        highlights?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  destinationIntro?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
      };
  serviceIntro?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
      };
  services?:
    | T
    | {
        index?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        actionLabel?: T;
        href?: T;
        id?: T;
      };
  process?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  trust?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
        actionLabel?: T;
        actionHref?: T;
      };
  consultation?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
        actionLabel?: T;
        actionHref?: T;
      };
  faqIntro?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        category?: T;
        showOnHomepage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-page_select".
 */
export interface ConsultationPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
      };
  durationMinutes?: T;
  priceAmount?: T;
  deliveryMethod?: T;
  documentsNote?: T;
  paymentNote?: T;
  cancellationPolicy?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}